-- AlterTable
ALTER TABLE "Lesson" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "lastStreakUpdate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
